package net.chuangdie.lhb.bean;

public class Shopping extends BasicBean
{
	private Integer id;
	private Double price;
	private String name;

	// private JdbcTemplate jdbcTemplate;

	public Shopping()
	{
		super.setObj(this);
		super.setTableName("shopping");
		super.setPrimaryKey("id");
	}

	public void createTable()
	{
		String sql = "create table shopping(" + "id int not null generated by default as identity,"
				+ "price double, name varchar(20))";
		sql = "insert into shopping (price , name ) values (10.02 , '你好' )";
		super.executeUpdate(sql);
	}

	// public int insert(Shopping shopping)
	// {
	// String sql = "insert into shopping (price, name)" + "values(?, ?)";
	// Object[] params = new Object[]
	// { shopping.getPrice(), shopping.getName() };
	// return jdbcTemplate.update(sql, params);
	// }
	//
	// public void setJdbcTemplate(JdbcTemplate jdbcTemplate)
	// {
	// this.jdbcTemplate = jdbcTemplate;
	// }

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Double getPrice()
	{
		return price;
	}

	public void setPrice(Double price)
	{
		this.price = price;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}
}
